# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: actas.proto for package 'trep'

require 'grpc'
require_relative './actas_pb'

module Trep
  module PublicatorService
    # Servicio del Publicator
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'trep.PublicatorService'

      rpc :PublishActa, ::Trep::ActaValida, ::Trep::Ack
    end

    Stub = Service.rpc_stub_class
  end
end
