# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: actas.proto

require 'google/protobuf'


descriptor_data = "\n\x0b\x61\x63tas.proto\x12\x04trep\"\x96\x02\n\nActaValida\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04mesa\x18\x02 \x01(\t\x12\x0f\n\x07recinto\x18\x03 \x01(\t\x12\x14\n\x0c\x64\x65partamento\x18\x04 \x01(\t\x12\x11\n\tprovincia\x18\x05 \x01(\t\x12\x11\n\tmunicipio\x18\x06 \x01(\t\x12;\n\x0evotos_partidos\x18\x07 \x03(\x0b\x32#.trep.ActaValida.VotosPartidosEntry\x12\x15\n\rvotos_validos\x18\x08 \x01(\x05\x12\x17\n\x0fvotos_invalidos\x18\t \x01(\x05\x1a\x34\n\x12VotosPartidosEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2?\n\x11PublicatorService\x12*\n\x0bPublishActa\x12\x10.trep.ActaValida\x1a\t.trep.Ackb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Trep
  ActaValida = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("trep.ActaValida").msgclass
  Ack = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("trep.Ack").msgclass
end
